# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20180116_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço'),
        ),
    ]
